import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { toBn } from "../lib/utils";
import { useApp } from "../lib/AppContext";

export default function LiveExam() {
  const { user, startLiveExam: onStartLiveExam, setView } = useApp();
  const [liveExams, setLiveExams] = useState([]); const [attendedIds, setAttendedIds] = useState(new Set()); const [isPremium, setIsPremium] = useState(false); const [now, setNow] = useState(Date.now()); const [loading, setLoading] = useState(true); const [leaderboardFor, setLeaderboardFor] = useState(null); const [leaderboardRows, setLeaderboardRows] = useState([]); const [loadingBoard, setLoadingBoard] = useState(false);
  useEffect(() => { load(); const tick = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(tick); }, []);
  async function load() { setLoading(true); const [{ data: exams }, { data: sessions }, { data: subs }] = await Promise.all([supabase.from("live_exams").select("*").order("start_at", { ascending: true }), supabase.from("practice_sessions").select("live_exam_id").eq("user_id", user.id).eq("mode", "live").not("live_exam_id", "is", null).not("completed_at", "is", null), supabase.from("subscriptions").select("expires_at").eq("user_id", user.id).eq("status", "approved").gt("expires_at", new Date().toISOString()).limit(1)]); setLiveExams(exams || []); setAttendedIds(new Set((sessions || []).map((s) => s.live_exam_id))); setIsPremium((subs || []).length > 0); setLoading(false); }
  async function openLeaderboard(le) { setLeaderboardFor({ id: le.id, title: le.title }); setLoadingBoard(true); const { data, error } = await supabase.rpc("live_exam_leaderboard", { p_live_exam_id: le.id }); if (!error) setLeaderboardRows(data || []); setLoadingBoard(false); }
  function statusOf(le) { const start = new Date(le.start_at).getTime(); const end = start + le.duration_minutes * 60000; if (now < start) return "upcoming"; if (now < end) return "ongoing"; return "ended"; }
  function countdown(le) { const diff = Math.max(0, new Date(le.start_at).getTime() - now); const sec = Math.floor(diff / 1000); const h = Math.floor(sec / 3600), m = Math.floor((sec % 3600) / 60), s = sec % 60; return `${toBn(String(h).padStart(2,"0"))}:${toBn(String(m).padStart(2,"0"))}:${toBn(String(s).padStart(2,"0"))}`; }
  async function handleJoin(le) { const start = new Date(le.start_at).getTime(), end = start + le.duration_minutes * 60000; const timeLimitSeconds = Math.min(le.duration_minutes * 60, Math.max(30, Math.floor((end - now) / 1000))); await onStartLiveExam(le, timeLimitSeconds); }
  if (leaderboardFor) return <section className="view live-page"><button className="back-link" onClick={() => setLeaderboardFor(null)}>← লাইভ পরীক্ষায় ফিরুন</button><div className="page-hero compact"><div><span className="eyebrow">LEADERBOARD</span><h1>🏆 {leaderboardFor.title}</h1><p>সবার স্কোরের ভিত্তিতে আপনার অবস্থান দেখুন। পরিচয় গোপন রাখা হয়।</p></div></div>{loadingBoard ? <LoadingState /> : leaderboardRows.length === 0 ? <EmptyState title="এখনো কোনো ফলাফল নেই" text="পরীক্ষা শেষ করার পর leaderboard-এ ফলাফল দেখা যাবে।" /> : <div className="leaderboard-card">{leaderboardRows.map((row) => <div key={row.rank} className={`leader-row ${row.is_me ? "me" : ""}`}><span className="rank-badge">{row.rank === 1 ? "🥇" : row.rank === 2 ? "🥈" : row.rank === 3 ? "🥉" : toBn(row.rank)}</span><span>{row.is_me ? "আপনি" : `Rank ${toBn(row.rank)}`}</span><strong>{toBn(row.correct_answers)} / {toBn(row.total_questions)}</strong></div>)}</div>}</section>;
  return <section className="view live-page"><div className="page-hero live-hero"><div><span className="eyebrow">LIVE EXAM</span><h1>🔴 লাইভ পরীক্ষা</h1><p>নির্ধারিত সময়ে পরীক্ষা দিন এবং অন্যদের সাথে আপনার স্কোর তুলনা করুন।</p></div><div className="live-status-pill"><i/> {isPremium ? "Premium Active" : "Free + Premium"}</div></div><div className="live-info-strip"><div><strong>🏆 Ranking</strong><span>নাম প্রকাশ ছাড়াই স্কোর তুলনা</span></div><div><strong>⏱ Timed</strong><span>নির্ধারিত সময়ে পরীক্ষা</span></div><div><strong>🔒 Fair Play</strong><span>সবার জন্য একই প্রশ্ন</span></div></div>{loading && <LoadingState />}{!loading && !liveExams.length && <EmptyState title="কোনো লাইভ পরীক্ষা নেই" text="Admin থেকে নতুন পরীক্ষা নির্ধারণ করা হলে এখানে দেখা যাবে।" />}{!loading && liveExams.length > 0 && <div className="live-exam-grid">{liveExams.map((le) => { const status = statusOf(le), attended = attendedIds.has(le.id), locked = !le.free_for_all && !isPremium; return <article className={`live-exam-card ${status}`} key={le.id}><div className="live-card-top"><span className={`status-badge ${status}`}>{status === "ongoing" ? "🔴 LIVE NOW" : status === "upcoming" ? "UPCOMING" : "ENDED"}</span>{!le.free_for_all && <span className="premium-badge">✦ Premium</span>}</div><h3>{le.title}</h3><div className="live-meta-grid"><span>📝 {toBn(le.question_count)} প্রশ্ন</span><span>⏱ {toBn(le.duration_minutes)} মিনিট</span><span>📅 {new Date(le.start_at).toLocaleDateString("bn-BD")}</span></div>{status === "upcoming" && <div className="countdown-box"><small>শুরু হতে বাকি</small><strong>{countdown(le)}</strong></div>}{status === "ongoing" && <div className="ongoing-note">এখন পরীক্ষা চলছে — সময় শেষ হওয়ার আগে যোগ দিন।</div>}{status === "ended" && <div className="ended-note">এই পরীক্ষা শেষ হয়েছে।</div>}<div className="live-card-actions">{status === "ongoing" && !attended && locked && <button className="cta-primary" onClick={() => setView("subscription")}>🔒 Premium নিন</button>}{status === "ongoing" && !attended && !locked && <button className="cta-primary" onClick={() => handleJoin(le)}>পরীক্ষায় যোগ দিন →</button>}{(status === "ended" || attended) && <button className="cta-ghost" onClick={() => openLeaderboard(le)}>🏆 Ranking দেখুন</button>}{status === "upcoming" && <button className="cta-ghost" disabled>অপেক্ষা করুন</button>}</div></article>; })}</div>}</section>;
}
function EmptyState({ title, text }) { return <div className="empty-state"><div>📭</div><h3>{title}</h3><p>{text}</p></div>; }
function LoadingState() { return <div className="loading-state"><span className="spinner"/>লোড হচ্ছে...</div>; }
